version: 2
jobs:

  mdl:
    docker:
      - image: rsrchboy/mdl
    steps:
      - checkout
      - run: mdl .

  flake8:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8 ddldump/

  postgres:
    docker:
      - image: python:2.7
      - image: hashicorp/terraform
      - image: registry.hub.docker.com/library/postgres:9.6.5-alpine
    steps:
      - checkout
      - run:
          command: terraform init
          working_directory: terraform/rds/
      - run:
          command: terraform apply
          working_directory: terraform/rds/
      - run: psql -h 127.0.0.1 -U ddldump ddldump < ddldump.sql
      - run: ddldump --diff=ddldump.sql postgresql://ddldump:ddldump@127.0.0.1:5432/ddldump

workflows:
  version: 2
  phaser:
    jobs:
      - mdl
      - flake8
