version: 2
jobs:

  mdl:
    docker:
      - image: rsrchboy/mdl
    steps:
      - checkout
      - run: mdl .

  flake8:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8 ddldump/

  postgres:
    docker:
      #- image: ubuntu:14.04
      #- image: hashicorp/terraform
      #- image: registry.hub.docker.com/library/postgres:9.6.5-alpine
      - image: ubuntu:14.04
      - image: circleci/postgres:9.6.8-alpine
      - image: python:2.7
        environment:
          POSTGRES_USER: ddldump
          POSTGRES_PASSWORD: ddldump
          #POSTGRES_DB: ddldump
          #PGUSER: ddldump
          #PGPASSWORD: ddldump
          #PGHOST: 127.0.0.1
          #PGDATABSE: ddldump
    steps:
      - checkout
      - run:
          name: Install postgresql-client
          command: |
            apt-get update
            apt-get -y install postgresql-client


      - run: psql -h 127.0.0.1 -U postgres < ddldump.sql
      - run: ddldump --diff=ddldump.sql postgresql://ddldump:ddldump@127.0.0.1:5432
      #- run:
          #command: terraform init
          #working_directory: ci/terraform/
      #- run:
          #command: terraform plan
          #working_directory: ci/terraform/
      #- run:
          #command: yes | terraform apply
          #working_directory: ci/terraform/

workflows:
  version: 2
  phaser:
    jobs:
      - mdl
      - flake8
      - postgres
